// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72j0BbmUuHAa9qcTcmjnpXxeIHHjeOno',
    appId: '1:1049312246718:web:882cfbb63b3ad0f94097ef',
    messagingSenderId: '1049312246718',
    projectId: 'all-the-films',
    authDomain: 'all-the-films.firebaseapp.com',
    storageBucket: 'all-the-films.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4i7H4rbLjEiGRRq3gygx0vFhWQlAcGOQ',
    appId: '1:1049312246718:android:afd0f05fe790619c4097ef',
    messagingSenderId: '1049312246718',
    projectId: 'all-the-films',
    storageBucket: 'all-the-films.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpLtXyK-FNDQ0L6DcNmM1Jzw3Yk4vwYY',
    appId: '1:1049312246718:ios:f07a45e36720ca9e4097ef',
    messagingSenderId: '1049312246718',
    projectId: 'all-the-films',
    storageBucket: 'all-the-films.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWpLtXyK-FNDQ0L6DcNmM1Jzw3Yk4vwYY',
    appId: '1:1049312246718:ios:f07a45e36720ca9e4097ef',
    messagingSenderId: '1049312246718',
    projectId: 'all-the-films',
    storageBucket: 'all-the-films.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA72j0BbmUuHAa9qcTcmjnpXxeIHHjeOno',
    appId: '1:1049312246718:web:3c80ceb460ae0a484097ef',
    messagingSenderId: '1049312246718',
    projectId: 'all-the-films',
    authDomain: 'all-the-films.firebaseapp.com',
    storageBucket: 'all-the-films.firebasestorage.app',
  );

}